### ISSUE TITLE
Internal Server Error - Accept a Non-Existent Federation Request

### ISSUE THREAD

**Issue by mathisonryan** [DBOMproject/chainsource-gateway#103]
**Your Environment**

- Versions of your services : 2.0.0-alpha
- Operating System : windows 11 Docker

**Describe the current behavior**

Returns Internal Server Error

**Describe the expected behavior**

Return request not found

**Standalone steps to reproduce the issue**

- Run the docker-compose-example-two-nodes example. 
- Attempt to accept a request with an id that does not exist.

**Other info / logs:** 

[accept-non-existent-fed-req.log](https://github.com/DBOMproject/chainsource-gateway/files/12404008/accept-non-existent-fed-req.log)

![image](https://github.com/DBOMproject/chainsource-gateway/assets/57193503/f517ab46-09be-4a80-81f6-cd764c1dc07d)

**Comment by mathisonryan** [comment]
Same behavior exists for reject request

**Comment by irajeshegde** [comment]
These edge cases are now handled and are updated in both the micro-services:
* [chainsource-gateway](https://github.com/DBOMproject/chainsource-gateway/commit/9dd7cd20a04b092ac71b385a97628808bb2fd3b8)
* [database-agent](https://github.com/DBOMproject/database-agent/commit/83ec572f54e7c63041ad8875c84672c6f6c6a1c9)

Examples can be found in [Postman Collection](https://github.com/DBOMproject/api-specs/tree/2.0.0-alpha-1/gateway/postman)
