### ISSUE TITLE
Database agent crashes when attempting to create a duplicate channel

### ISSUE THREAD

**Issue by akshayakhare** [DBOMproject/chainsource-gateway#106]
Environment:

- Version: 2.0.0-alpha-1
- Operating System: Ubuntu 22.04 LTS
  - Codename: Jammy

**Current Behavior:** When trying to create a *duplicate* channel id, the database agent crashes with this error
```
2023-09-05T14:47:28.292Z info   [channel] #4 handling [create]
2023-09-05T14:47:29.702Z error  Failed to create channel: 
Invalid `prisma.channel.create()` invocation in
/usr/src/app/controller/channel.js:27:42

  24 try {
  25   const { channelMeta } = JSON.parse(requestData);
  26   const { channelId, description, type, notaries } = channelMeta;
→ 27   const channel = await prisma.channel.create(
Unique constraint failed on the constraint: `channel_channelId_key`
(node:194) UnhandledPromiseRejectionWarning: Error: Failed to create channel
    at createChannel (/usr/src/app/controller/channel.js:40:11)
    at async /usr/src/app/index.js:193:26
(Use `node --trace-warnings ...` to show where the warning was created)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Once the agent crashes, none of the commands work as expected, and the logs for the database agent are stuck at this error. Although the Container is still intact.

**Describe the expected behavior**
On trying to create a duplicate channel id, it should be able to handle the error by sending back the appropriate message, and not crash the database agent.

**Standalone steps to reproduce the issue**
- Create a new channel
- Create the same channel again with the same ID as the first one

**Comment by irajeshegde** [comment]
@akshayakhare  - This is now fixed. And same docker images are updated. Refer - [commit](https://github.com/DBOMproject/chainsource-gateway/commit/488018f9fc0867eb8af171f1311a44e6ed0df8f0)
